AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sends an email when an object with prefix '/img' is deleted from an S3 bucket.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3testing81938387  # The bucket will be created with this name
  
  S3DeleteNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./s3
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Policies:
        - AmazonS3FullAccess
        - AmazonSESFullAccess
      Environment:
        Variables:
          BUCKET_NAME: s3testing81938387
          DEST_EMAIL: "nischith.818@gmail.com"
      Events:
        S3DeleteEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket  # Refers to the S3 bucket created in this template
            Events:
              - s3:ObjectRemoved:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: img/

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: The S3 bucket name
