AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sends an email when an object with prefix '/img' is deleted from an S3 bucket.

Resources:
  S3DeleteNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Policies:
        - AmazonS3FullAccess
        - AmazonSESFullAccess
      Environment:
        Variables:
          BUCKET_NAME: s3testing81938387
          DEST_EMAIL: "nischith.818@gmail.com"
      Events:
        S3DeleteEvent:
          Type: S3
          Properties:
            Bucket: s3testing81938387
            Events:
              - s3:ObjectRemoved:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: img/

Outputs:
  BucketName:
    Value: s3testing81938387
    Description: The S3 bucket name
