AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sends an email when an object with prefix '/img' is deleted from the S3 bucket `s3testing81938387`.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3testing81938387

  S3DeleteNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Policies:
        - AmazonS3FullAccess
        - AmazonSESFullAccess
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3Bucket
          DEST_EMAIL: "your_email@example.com" # Update with your email
      Events:
        S3DeleteEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket # Reference the same S3 bucket
            Events:
              - s3:ObjectRemoved:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: img/

  S3BucketNotificationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt S3DeleteNotificationFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${S3Bucket}

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: The S3 bucket name
