AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Sends an email when an object with prefix '/img' is deleted from the S3 bucket.

Resources:
  S3DeleteNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./s3
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 10
      MemorySize: 128
      Policies:
        - AmazonS3FullAccess
        - AmazonSESFullAccess
      Environment:
        Variables:
          DEST_EMAIL: "nischith.818@gmail.com"
      Events:
        S3DeleteEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events:
              - s3:ObjectRemoved:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: img/

  ImagesBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: s3testing8193838792
